
TARGET=build/guest2
SRC_DIRS=src drivers/ovp/uart

# libraries
INC_DIRS=../library/include ../../library/include
LIB_DIRS = ../library/build ../../library/build
LIB_FILES=task minic

include ../make2.inc 
